### ISSUE TITLE
ConfigParser Exceptions Fail in Plugins

### ISSUE THREAD

**Issue by grahams** [grahams/trackupdate#2]
ConfigParser Exceptions fail in Plugin init because ConfigParser is not imported:

```
xxx:nicecast-trackupdate copy xxx$ python trackupdate.py
Traceback (most recent call last):
  File "trackupdate.py", line 176, in <module>
    trackUpdate = TrackUpdate(sys.argv[1:])
  File "trackupdate.py", line 90, in __init__
    self.loadPlugins(config, self.episodeNumber)
  File "trackupdate.py", line 170, in loadPlugins
    o = cls(config,episode)
  File "./plugins/NicecastTarget.py", line 41, in __init__
    except ConfigParser.NoSectionError:
NameError: global name 'ConfigParser' is not defined
```

**Comment by grahams** [comment]
This should be resolved now that python3 won't let us get away with that.
